### ISSUE TITLE
I could not install LightMock with netcore

### ISSUE THREAD

**Issue by rosslight** [seesharper/LightMock#11]
i have try to install the lightmock to my .netcore unit test project, but i get the following error, could you help to fix the issue?

---------------------------------------------------------------------------------------------------
 Install-Package : Package LightMock.vNext 1.0.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1).

  Package LightMock.vNext 1.0.1 supports:
  - dnx451 (DNX,Version=v4.5.1)
  - dnxcore50 (DNXCore,Version=v5.0)
At line:1 char:16

+ Install-Package <<<<  LightMock.vNext 
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:16
+ Install-Package <<<<  LightMock.vNext 
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'FunctionDemo'.
At line:1 char:16
+ Install-Package <<<<  LightMock.vNext 
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by seesharper** [comment]
LightMock.vNext is a fork that is not maintained here. I will however have a look at see if we can get .Net Core support in repo as well

**Comment by seesharper** [comment]
LightMock v1.0.1 has just been published to NuGet. It is now NetStandard 1.0

**Comment by rosslight** [comment]
Thank you , let me try.
