### ISSUE TITLE
UWP Compatibility

### ISSUE THREAD

**Issue by anton-yashin** [seesharper/LightMock#14]
Latest UWP SDK's doesn't work properly with netstandard 1.0 assembly of LightMock in release mode. You need to change `<TargetFramework>netstandard1.0</TargetFramework>` to `<TargetFrameworks>netstandard1.0;netstandard2.0</TargetFrameworks>` in LightMock.csproj file to fix this. I also can provide a pull request with xunit tests and uwp test runner.

**Comment by seesharper** [comment]
Hi . I don't really think we need to support netstandard1.0 anymore. Just bump the whole thing to netstandard2.0 👍😀
